name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  build:
    name: CI (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    strategy:
      matrix:
        include:
          - elixir: 1.15.7
            otp: 26.2
            check_formatted: false
            run_assay: false
          - elixir: 1.16.1
            otp: 26.2
            check_formatted: false
            run_assay: false
          - elixir: 1.17.3
            otp: 27.1.1
            check_formatted: false
            run_assay: false
          - elixir: 1.18.3
            otp: 27.3.3
            check_formatted: true
            run_assay: true
          - elixir: 1.19.5
            otp: 28.5.0.1
            check_formatted: true
            run_assay: true
          - elixir: 1.20.0
            otp: 29.0.1
            check_formatted: true
            run_assay: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v5
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - run: mix deps.get

      - name: Check formatting
        if: ${{ matrix.check_formatted }}
        run: mix format --check-formatted

      - run: mix compile --warnings-as-errors
      - run: mix credo --strict
      - run: mix test --exclude integration
        env:
          MIX_ENV: test
      - name: Run assay
        if: ${{ matrix.run_assay }}
        run: mix assay
